server:
  port: 8080
spring:
  application:
    name: accounts
build:
  version: "1.0"
accounts:
  message: "Welcome to EazyBank accounts related local APIs "
  contactDetails:
    name: "Test - Developer"
    email: "test@eazybank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345